# Generated by Django 3.2.5 on 2021-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('detail_subject', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
