# Generated by Django 3.2.5 on 2021-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
